--Integrity Tests
--Insert Into Inventory (Inventory_Id, Maximum_Space, Occupied_Space) Values (1, 5, 2);
--Insert Into Characters_Passives (Character_Id, Passive_Name) Values (2, 'BOB')
--Insert Into Characters (Character_Name, HP, Atk, Def, UID, Head) Values ('Hello_Bob', 1, 0, 1000000, 1, 2);

--Type Tests
--Insert Into Equipment (Name, Type, Description, HP, Atk, Def) Values ('DIO', 'Legs', 'Pathetic Humans cannot stand up to the wearer of these Leggings', '1', 1, 1);
--Insert Into Equipment (Name, Type, Description, HP, Atk, Def) Values ( 23, 'Legs', 'El Mundo', 1, 1, 1);
--Insert Into Equipment (Name, Type, Description, HP, Atk, Def) Values ( 2, 'Legs', 'El Mundo', 1, 1, 1)
--Insert Into Items (Item_Name, Type, Description, Effect) Values ('Potion', 'Consumable', 'Do not die idiot', 'Heals an idiot')
--Insert Into Profiles (Name, Password, Email) Values ('Eric Cartman', 'Whasup', 'BestMail@Gmail.com')
--Insert Into Equipment (Name, Type, Description, HP, Atk, Def) Values ( 2, 'Legs', 'El Mundo', 1, 1, 1)
--Insert Into Items(Type, Description, Effect) Values ('Ingridient', 'Empty', 'Does random nothing');
